<Project>
  <PropertyGroup>
    <!--metadaata of assemblies-->
    <Authors>Ehsan Vali</Authors>
    <Company>Gooya Systems</Company>
    <Product>Sayeh</Product>

    <!--settings of projects-->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>

  </PropertyGroup>
</Project>
